# Generated by Django 5.1.1 on 2024-09-28 04:56

import Users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=Users.utils.user_directory_path),
        ),
    ]
